PCAP_FILE = "/tshark/01.pcap"

DOS_THRESHOLD = 1000
PORTSCAN_THRESHOLD = 20
BRUTEFORCE_THRESHOLD = 15

TIME_WINDOW = 10  # секунд
LOG_FILE = "ids_log.txt"

SMTP_USER = ""
SMTP_PASSWORD = ""
ADMIN_EMAIL = ""
SMTP_SERVER = ""
SMTP_PORT = "25"
